# Generated by Django 3.0.2 on 2020-01-31 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('website', models.URLField(verbose_name='Website Link')),
            ],
        ),
    ]
