# Generated by Django 3.0.2 on 2020-01-31 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0001_initial'),
        ('otp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='merchant_id',
            field=models.ForeignKey(default='12', on_delete=django.db.models.deletion.CASCADE, to='merchant.Merchant'),
            preserve_default=False,
        ),
    ]
